project:
  type: website
  output-dir: docs

website:
  title: "Morgan Mathison"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - href: PostbacResearch.qmd
        text: Postbac Research
      - href: UndergradResearch.qmd
        text: Undergrad Research
      - href: presentations.qmd
        text: Posters and Presentations
        
format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

