project:
  type: website
  output-dir: docs

website:
  title: "Morgan Mathison"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - href: UndergradResearch.qmd
        text: Undergrad Research
      - href: presentations.qmd
        text: Presentations
      - href: FloralArtistry.qmd
        text: Floral Artisty
        
format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

