project:
  type: website

website:
  title: "Morgan Mathison"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - href: about.qmd
        text: Projects
      - href: presentations.qmd
        text: Presentations
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

